name: CI Staging

on:
  push:
    branches:
      - staging

concurrency:
  group: ci-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/ci-reusable.yml
